#!/usr/bin/env python3
import argparse

class Purge:
    def __init__(self):
        # Arguments
        self.args = None

    def get_arguments(self):
        # Setting & Getting Parameters
        parser = argparse.ArgumentParser(description='Command to purge (delete) files')
        subparsers = parser.add_subparsers(dest='command', help='Sub-command help')

        # Purge subparser
        purge_parser = subparsers.add_parser('purge', help='Purge files')
        purge_parser.add_argument('-a', '--all', action='store_true', help='Delete all files')
        purge_parser.add_argument('-u', '--unlocked', action='store_true', help='Delete all files that don\'t have the .locked extension')
        purge_parser.add_argument('-l', '--locked', action='store_true', help='Delete all files with the .locked extension')
        purge_parser.add_argument('-s', '--specific', metavar='EXT', nargs='+', help='Specific file extensions to delete (separated by commas)')
        purge_parser.add_argument('-d', '--directories', metavar='EXT', nargs='+', help='Specify what directories you wish to purge (Default is current)')

        self.args = parser.parse_args()

        if self.args.command != 'purge':
            parser.error('Please provide a valid command. Use "purge" to delete files.')


    def perform_action(self):
        pass

if __name__ == "__main__":
    purge = Purge()
    purge.get_arguments()